services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Teste12345!"   
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  webapi:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:8080"
      Firebase__ProjectId: "o_teu_projectId"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=alma_app_dev;User Id=sa;Password=Teste12345!;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True" # <<< QUOTED
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  mssql_data:
